        ('Brussels Roulette'),
        ('Roleta Brasileira'),
        ('Express Ruleta'),
        ('Age of the Gods Bonus Roulette'),
        ('American Roulette'),
        ('Deutsches Roulette'),
        ('Greek Quantum Roulette'),
        ('Greek Roulette'),
        ('Hindi Roulette'),
        ('Live Football French Roulette'),
        ('Live Football Roulette'),
        ('Live French Roulette'),
        ('Mega FireBlaze Roulette'),
        ('Prestige Roulette'),
        ('Speed Auto Roulette'),
        ('Bucharest Quantum Roulette'),
        ('Quantum Roulette'),
        ('Roulette Italiana'),
        ('Roulette'),
        ('Auto Roulette'),
        ('Speed Roulette'),
        ('Bucharest Roulette'),
        ('Turkish Roulette'),
        ('UK Roulette'),
        ('Who Wants To Be A Millionaire Roulette'),
        ('Ruyi Roulette'),
        ('Slingshot Ruleta Espana'),
        ('Ruleta Automatica Cuantica'),
        ('Ruyi French Roulette'),
        ('Quantum Ruleta Espana'),
        ('x1000 Quantum Roulette'),
        ('Arabic Roulette'),
        ('Peru Spread Bet Roulette'),
        ('Auto Roulette 2'),

    
        ('Speed Roulette'),
        ('Mega Roulette'),
        ('Roulette 1 Azure'),
        ('Roulette 2'),
        ('Roulette 3 Macao'),
        ('Auto Roulette 1'),
        ('Roulette 6 Turkish'),
        ('Roulette 4 Russian'),
        ('Roulette 5 German'),
        ('Roulette 7 Italian'),
        ('Roulette 8 Indian'),
        ('Roulette 9 The Club'),
        ('Roulette 10 Ruby'),
        ('Roulette 12 Romanian'),
        ('Roulette 14 Spanish'),
        ('PowerUp Roulette'),
        ('Speed Auto Roulette'),
        ('Auto Mega Roulette')
    
    
        ('Roleta ao vivo'),
        ('Lightning Roulette'),
        ('Roulette'),
        ('Immersive Roulette'),
        ('Instant Roulette'),
        ('Auto-Roulette'),
        ('Speed Roulette'),
        ('VIP Roulette'),
        ('Grand Casino Roulette'),
        ('French Roulette Gold'),
        ('American Roulette'),
        ('Double Ball Roulette'),
        ('Speed Auto Roulette'),
        ('Auto-Roulette VIP'),
        ('Benelux Slingshot'),
        ('London Roulette'),
        ('Salon Privé Roulette'),
        ('Casino Malta Roulette'),
        ('Arabic Roulette'),
        ('Deutsches Roulette'),
        ('Roulette Francophone'),
        ('La Partage Francophone'),
        ('Norsk Roulette'),
        ('Ruletka Live'),
        ('Suomalainen Ruletti'),
        ('Svensk Roulette'),
        ('Japanese Roulette'),
        ('Türkçe Rulet 2'),
        ('Venezia Roulette'),
        ('Venezia La Partage'),
        ('Bucharest Roulette'),
        ('Bucharest Auto-Roulette'),
        ('Auto Lightning Roulette'),
        ('First Person American Roulette'),
        ('First Person Lightning Roulette'),
        ('First Person Roulette'),
        ('Türkçe Lightning Rulet'),
        ('XXXTreme Lightning Roulette'),
        ('Dragonara Roulette'),
        ('Ruleta Bola Rapida en Vivo'),
        ('Italian Lightning Roulette'),
        ('Korean Dealer Lightning Roulette'),
        ('Hindi Lightning Roulette'),
        ('Roleta Relâmpago'),
        ('Benelux Slingshot')
    